create table branches(
                         id integer generated by default as identity primary key,
                         name varchar,
                         address varchar,
                         work_hours varchar,
                         contact_information varchar

);

create table customers
(id integer generated by default as identity primary key ,
 firstname varchar,
 lastname varchar,
 email varchar,
 phone_number varchar,
 creation_date timestamp);

create table cars(
                     id integer generated by default as identity primary key ,
                     branch_id integer references branches(id),
                     brand varchar,
                     model varchar,
                     year_of_production integer,
                     plate_number varchar,
                     car_condition boolean
);

create table reservations(
                             id integer generated by default as identity primary key,
                             customer_id integer references customers(id),
                             car_id integer references cars(id),
                             start_date_time timestamp,
                             end_date_time timestamp,
                             price integer,
                             booking_status varchar
);

create table transactions(
                             id integer generated by default as identity primary key,
                             customer_id integer references customers(id),
                             amount integer,
                             creation_date timestamp
);