create table branches(
                         id integer generated by default as identity primary key,
                         name varchar NOT NULL ,
                         address varchar NOT NULL ,
                         work_hours varchar NOT NULL ,
                         contact_information varchar NOT NULL

);

create table customers
(id integer generated by default as identity primary key ,
 firstname varchar NOT NULL ,
 lastname varchar NOT NULL ,
 email varchar unique ,
 phone_number varchar unique ,
 creation_date timestamp not null );

create table cars(
                     id integer generated by default as identity primary key ,
                     branch_id integer references branches(id),
                     brand varchar not null ,
                     model varchar not null ,
                     year_of_production integer not null ,
                     plate_number varchar not null unique ,
                     is_available boolean default false
);

create table reservations(
                             id integer generated by default as identity primary key,
                             customer_id integer references customers(id),
                             car_id integer references cars(id),
                             start_date_time timestamp not null ,
                             end_date_time timestamp,
                             price integer not null ,
                             booking_status varchar not null
);

create table transactions(
                             id integer generated by default as identity primary key,
                             customer_id integer references customers(id),
                             amount integer not null ,
                             creation_date timestamp not null
);