alter table car_order_service_db.public.places
    drop column contact_information;

alter table car_order_service_db.public.customers
    rename to users;

alter table users
    add password varchar default null;

alter table users
    add role varchar default null;

alter table car_order_service_db.public.cars
add daily_fee decimal default null;

create unique index reservations_car_id_uindex
    on car_order_service_db.public.reservations (car_id);

alter table car_order_service_db.public.reservations
    drop column price;

drop table car_order_service_db.public.transactions;

create table car_order_service_db.public.payments(
    id integer primary key generated by default as identity,
    reservation_id integer references car_order_service_db.public.reservations(id) unique,
    session_id varchar,
    status varchar,
    url varchar
)