drop table car_order_service_db.public.payments;

create table car_order_service_db.public.payments(
                                                     id integer primary key generated by default as identity,
                                                     reservation_id integer references users(id),
                                                     session_id varchar,
                                                     status varchar,
                                                     url varchar
);

alter table car_order_service_db.public.reservations
rename customer_id to user_id;

